swagger: "2.0"
info:
  version: "1.0.0"
  title: "Mate Exam API"
  description: "A simple API to give test exams to students"
host: "agentmate.herokuapp.com"
basePath: "/api/v1"
tags:
- name: "students"
  description: "students"
- name: "exams"
  description: "exam question sheets"
- name: "results"
  description: "submitting and reading exam results of students"
schemes:
- "https"
paths:
  /students:
    get:
      tags:
      - "students"
      summary: "Get list of all students"
      operationId: "getStudents"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Student"
  /students/{id}:
    get:
      tags:
      - "students"
      summary: "Get a student by id"
      operationId: "getStudentById"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of student to return"
        required: true
        type: "hexadecimal"
    responses:
      200:
        description: "successful operation"
        schema:
          $ref: "#/definitions/Student"





definitions:
 Student:
    type: "object"
    properties:
      _id:
        type: "string"
        format: "hexadecimal"
        description: "mLab generated mongodb field"
        example: "12312d1231b"
      name:
        type: "string"
        format: "First Middle Last"
        description: "Full name of the student"
        example: "Христо Евлогиев Георгиев"
      phone:
        type: "string"
        example: "032/222222"
      address:
        type: "string"
        example: "ул. Възрожденска 1А, Пловдив, 4000"
    xml:
      name: "Student"