swagger: "2.0"
info:
  version: "1.0.0"
  title: "Mate Exam API"
  description: "A simple API to give test exams to students"
host: "agentmate.herokuapp.com"
basePath: "/api/v1"
tags:
- name: "students"
  description: "Everything about students"
- name: "exams"
  description: "Everything about exam question sheets"
- name: "results"
  description: "Everything about exam results of students who have taken exams"
schemes:
- "https"
paths:
  /students:
    get:
      tags:
      - "students"
      summary: "Get list of all students"
      operationId: "getStudents"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Student"
        500:
          description: "Database error message"
definitions:
 Student:
    type: "object"
    properties:
      _id:
        type: "string"
        format: "hexadecimal"
        description: "mLab generated mongodb field"
      name:
        type: "string"
        format: "First Middle Last"
        description: "Full name of the student"
      phone:
        type: "string"
      address:
        type: "string"
    xml:
      name: "Student"